//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuxiliaryLibraries.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuxiliaryLibraries.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string day1 {
            get {
                return ResourceManager.GetString("day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenth.
        /// </summary>
        internal static string day10 {
            get {
                return ResourceManager.GetString("day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دهم.
        /// </summary>
        internal static string day10Persian {
            get {
                return ResourceManager.GetString("day10Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleventh.
        /// </summary>
        internal static string day11 {
            get {
                return ResourceManager.GetString("day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یازدهم.
        /// </summary>
        internal static string day11Persian {
            get {
                return ResourceManager.GetString("day11Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelfth.
        /// </summary>
        internal static string day12 {
            get {
                return ResourceManager.GetString("day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوازدهم.
        /// </summary>
        internal static string day12Persian {
            get {
                return ResourceManager.GetString("day12Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirteenth.
        /// </summary>
        internal static string day13 {
            get {
                return ResourceManager.GetString("day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیزدهم.
        /// </summary>
        internal static string day13Persian {
            get {
                return ResourceManager.GetString("day13Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourteenth.
        /// </summary>
        internal static string day14 {
            get {
                return ResourceManager.GetString("day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهاردهم.
        /// </summary>
        internal static string day14Persian {
            get {
                return ResourceManager.GetString("day14Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifteenth.
        /// </summary>
        internal static string day15 {
            get {
                return ResourceManager.GetString("day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پانزدهم.
        /// </summary>
        internal static string day15Persian {
            get {
                return ResourceManager.GetString("day15Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixteenth.
        /// </summary>
        internal static string day16 {
            get {
                return ResourceManager.GetString("day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شانزدهم.
        /// </summary>
        internal static string day16Persian {
            get {
                return ResourceManager.GetString("day16Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventeenth.
        /// </summary>
        internal static string day17 {
            get {
                return ResourceManager.GetString("day17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفدهم.
        /// </summary>
        internal static string day17Persian {
            get {
                return ResourceManager.GetString("day17Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighteenth.
        /// </summary>
        internal static string day18 {
            get {
                return ResourceManager.GetString("day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هجدهم.
        /// </summary>
        internal static string day18Persian {
            get {
                return ResourceManager.GetString("day18Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nineteenth.
        /// </summary>
        internal static string day19 {
            get {
                return ResourceManager.GetString("day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوزدهم.
        /// </summary>
        internal static string day19Persian {
            get {
                return ResourceManager.GetString("day19Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکم.
        /// </summary>
        internal static string day1Persian {
            get {
                return ResourceManager.GetString("day1Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string day2 {
            get {
                return ResourceManager.GetString("day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twentieth.
        /// </summary>
        internal static string day20 {
            get {
                return ResourceManager.GetString("day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیستم.
        /// </summary>
        internal static string day20Persian {
            get {
                return ResourceManager.GetString("day20Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-first.
        /// </summary>
        internal static string day21 {
            get {
                return ResourceManager.GetString("day21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست و یکم.
        /// </summary>
        internal static string day21Persian {
            get {
                return ResourceManager.GetString("day21Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-second.
        /// </summary>
        internal static string day22 {
            get {
                return ResourceManager.GetString("day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست و دوم.
        /// </summary>
        internal static string day22Persian {
            get {
                return ResourceManager.GetString("day22Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-third.
        /// </summary>
        internal static string day23 {
            get {
                return ResourceManager.GetString("day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست و سوم.
        /// </summary>
        internal static string day23Persian {
            get {
                return ResourceManager.GetString("day23Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-fourth.
        /// </summary>
        internal static string day24 {
            get {
                return ResourceManager.GetString("day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست و چهارم.
        /// </summary>
        internal static string day24Persian {
            get {
                return ResourceManager.GetString("day24Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-fifth.
        /// </summary>
        internal static string day25 {
            get {
                return ResourceManager.GetString("day25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست و پنجم.
        /// </summary>
        internal static string day25Persian {
            get {
                return ResourceManager.GetString("day25Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-sixth.
        /// </summary>
        internal static string day26 {
            get {
                return ResourceManager.GetString("day26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست و ششم.
        /// </summary>
        internal static string day26Persian {
            get {
                return ResourceManager.GetString("day26Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-seventh.
        /// </summary>
        internal static string day27 {
            get {
                return ResourceManager.GetString("day27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست و هفتم.
        /// </summary>
        internal static string day27Persian {
            get {
                return ResourceManager.GetString("day27Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-eighth.
        /// </summary>
        internal static string day28 {
            get {
                return ResourceManager.GetString("day28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست و هشتم.
        /// </summary>
        internal static string day28Persian {
            get {
                return ResourceManager.GetString("day28Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twenty-ninth.
        /// </summary>
        internal static string day29 {
            get {
                return ResourceManager.GetString("day29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست و نهم.
        /// </summary>
        internal static string day29Persian {
            get {
                return ResourceManager.GetString("day29Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوم.
        /// </summary>
        internal static string day2Persian {
            get {
                return ResourceManager.GetString("day2Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        internal static string day3 {
            get {
                return ResourceManager.GetString("day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirtieth.
        /// </summary>
        internal static string day30 {
            get {
                return ResourceManager.GetString("day30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سی ام.
        /// </summary>
        internal static string day30Persian {
            get {
                return ResourceManager.GetString("day30Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirty-first.
        /// </summary>
        internal static string day31 {
            get {
                return ResourceManager.GetString("day31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سی و یکم.
        /// </summary>
        internal static string day31Persian {
            get {
                return ResourceManager.GetString("day31Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوم.
        /// </summary>
        internal static string day3Persian {
            get {
                return ResourceManager.GetString("day3Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        internal static string day4 {
            get {
                return ResourceManager.GetString("day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارم.
        /// </summary>
        internal static string day4Persian {
            get {
                return ResourceManager.GetString("day4Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth.
        /// </summary>
        internal static string day5 {
            get {
                return ResourceManager.GetString("day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجم.
        /// </summary>
        internal static string day5Persian {
            get {
                return ResourceManager.GetString("day5Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixth.
        /// </summary>
        internal static string day6 {
            get {
                return ResourceManager.GetString("day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ششم.
        /// </summary>
        internal static string day6Persian {
            get {
                return ResourceManager.GetString("day6Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventh.
        /// </summary>
        internal static string day7 {
            get {
                return ResourceManager.GetString("day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتم.
        /// </summary>
        internal static string day7Persian {
            get {
                return ResourceManager.GetString("day7Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighth.
        /// </summary>
        internal static string day8 {
            get {
                return ResourceManager.GetString("day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشتم.
        /// </summary>
        internal static string day8Persian {
            get {
                return ResourceManager.GetString("day8Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninth.
        /// </summary>
        internal static string day9 {
            get {
                return ResourceManager.GetString("day9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهم.
        /// </summary>
        internal static string day9Persian {
            get {
                return ResourceManager.GetString("day9Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string DayAgo {
            get {
                return ResourceManager.GetString("DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} روز پیش.
        /// </summary>
        internal static string DayAgoPersian {
            get {
                return ResourceManager.GetString("DayAgoPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Days Later.
        /// </summary>
        internal static string DayLater {
            get {
                return ResourceManager.GetString("DayLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} روز بعد.
        /// </summary>
        internal static string DayLaterPersian {
            get {
                return ResourceManager.GetString("DayLaterPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایگان.
        /// </summary>
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        internal static string FridayPersian {
            get {
                return ResourceManager.GetString("FridayPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        internal static string HourAgo {
            get {
                return ResourceManager.GetString("HourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ساعت پیش.
        /// </summary>
        internal static string HourAgoPersian {
            get {
                return ResourceManager.GetString("HourAgoPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just right now.
        /// </summary>
        internal static string JustRightNow {
            get {
                return ResourceManager.GetString("JustRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همین الآن.
        /// </summary>
        internal static string JustRightNowPersian {
            get {
                return ResourceManager.GetString("JustRightNowPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minuts ago.
        /// </summary>
        internal static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} دقیقه پیش.
        /// </summary>
        internal static string MinutesAgoPersian {
            get {
                return ResourceManager.GetString("MinutesAgoPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        internal static string MondayPersian {
            get {
                return ResourceManager.GetString("MondayPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string Month1 {
            get {
                return ResourceManager.GetString("Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string Month10 {
            get {
                return ResourceManager.GetString("Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دی.
        /// </summary>
        internal static string Month10Persian {
            get {
                return ResourceManager.GetString("Month10Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Month11 {
            get {
                return ResourceManager.GetString("Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهمن.
        /// </summary>
        internal static string Month11Persian {
            get {
                return ResourceManager.GetString("Month11Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Month12 {
            get {
                return ResourceManager.GetString("Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسفند.
        /// </summary>
        internal static string Month12Persian {
            get {
                return ResourceManager.GetString("Month12Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرودین.
        /// </summary>
        internal static string Month1Persian {
            get {
                return ResourceManager.GetString("Month1Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string Month2 {
            get {
                return ResourceManager.GetString("Month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اردیبهشت.
        /// </summary>
        internal static string Month2Persian {
            get {
                return ResourceManager.GetString("Month2Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string Month3 {
            get {
                return ResourceManager.GetString("Month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خردادد.
        /// </summary>
        internal static string Month3Persian {
            get {
                return ResourceManager.GetString("Month3Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Month4 {
            get {
                return ResourceManager.GetString("Month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیر.
        /// </summary>
        internal static string Month4Persian {
            get {
                return ResourceManager.GetString("Month4Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Month5 {
            get {
                return ResourceManager.GetString("Month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرداد.
        /// </summary>
        internal static string Month5Persian {
            get {
                return ResourceManager.GetString("Month5Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهریور.
        /// </summary>
        internal static string Month6Persian {
            get {
                return ResourceManager.GetString("Month6Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string Month7 {
            get {
                return ResourceManager.GetString("Month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهر.
        /// </summary>
        internal static string Month7Persian {
            get {
                return ResourceManager.GetString("Month7Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string Month8 {
            get {
                return ResourceManager.GetString("Month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبان.
        /// </summary>
        internal static string Month8Persian {
            get {
                return ResourceManager.GetString("Month8Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Month9 {
            get {
                return ResourceManager.GetString("Month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آذر.
        /// </summary>
        internal static string Month9Persian {
            get {
                return ResourceManager.GetString("Month9Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        internal static string MonthAgo {
            get {
                return ResourceManager.GetString("MonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ماه پیش.
        /// </summary>
        internal static string MonthAgoPersian {
            get {
                return ResourceManager.GetString("MonthAgoPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Months Later.
        /// </summary>
        internal static string MonthLater {
            get {
                return ResourceManager.GetString("MonthLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ماه بعد.
        /// </summary>
        internal static string MonthLaterPersian {
            get {
                return ResourceManager.GetString("MonthLaterPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیلیارد.
        /// </summary>
        internal static string Number_Billiard {
            get {
                return ResourceManager.GetString("Number_Billiard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیلیون.
        /// </summary>
        internal static string Number_Billion {
            get {
                return ResourceManager.GetString("Number_Billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشت.
        /// </summary>
        internal static string Number_Eight {
            get {
                return ResourceManager.GetString("Number_Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هجده.
        /// </summary>
        internal static string Number_Eighteen {
            get {
                return ResourceManager.GetString("Number_Eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشتصد.
        /// </summary>
        internal static string Number_EightHundred {
            get {
                return ResourceManager.GetString("Number_EightHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشتاد.
        /// </summary>
        internal static string Number_Eighty {
            get {
                return ResourceManager.GetString("Number_Eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یازده.
        /// </summary>
        internal static string Number_Eleven {
            get {
                return ResourceManager.GetString("Number_Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پانزده.
        /// </summary>
        internal static string Number_Fifteen {
            get {
                return ResourceManager.GetString("Number_Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجاه.
        /// </summary>
        internal static string Number_Fifty {
            get {
                return ResourceManager.GetString("Number_Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنج.
        /// </summary>
        internal static string Number_Five {
            get {
                return ResourceManager.GetString("Number_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پانصد.
        /// </summary>
        internal static string Number_FiveHundred {
            get {
                return ResourceManager.GetString("Number_FiveHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهار.
        /// </summary>
        internal static string Number_Four {
            get {
                return ResourceManager.GetString("Number_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارصد.
        /// </summary>
        internal static string Number_FourHundred {
            get {
                return ResourceManager.GetString("Number_FourHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارده.
        /// </summary>
        internal static string Number_Fourteen {
            get {
                return ResourceManager.GetString("Number_Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهل.
        /// </summary>
        internal static string Number_Fourty {
            get {
                return ResourceManager.GetString("Number_Fourty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میلیارد.
        /// </summary>
        internal static string Number_Milliard {
            get {
                return ResourceManager.GetString("Number_Milliard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میلیون.
        /// </summary>
        internal static string Number_Million {
            get {
                return ResourceManager.GetString("Number_Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نه.
        /// </summary>
        internal static string Number_Nine {
            get {
                return ResourceManager.GetString("Number_Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهصد.
        /// </summary>
        internal static string Number_NineHundred {
            get {
                return ResourceManager.GetString("Number_NineHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوزده.
        /// </summary>
        internal static string Number_Nineteen {
            get {
                return ResourceManager.GetString("Number_Nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نود.
        /// </summary>
        internal static string Number_Ninety {
            get {
                return ResourceManager.GetString("Number_Ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک.
        /// </summary>
        internal static string Number_One {
            get {
                return ResourceManager.GetString("Number_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صد.
        /// </summary>
        internal static string Number_OneHundred {
            get {
                return ResourceManager.GetString("Number_OneHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفت.
        /// </summary>
        internal static string Number_Seven {
            get {
                return ResourceManager.GetString("Number_Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتصد.
        /// </summary>
        internal static string Number_SevenHundred {
            get {
                return ResourceManager.GetString("Number_SevenHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفده.
        /// </summary>
        internal static string Number_Seventeen {
            get {
                return ResourceManager.GetString("Number_Seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتاد.
        /// </summary>
        internal static string Number_Seventy {
            get {
                return ResourceManager.GetString("Number_Seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شش.
        /// </summary>
        internal static string Number_Six {
            get {
                return ResourceManager.GetString("Number_Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ششصد.
        /// </summary>
        internal static string Number_SixHundred {
            get {
                return ResourceManager.GetString("Number_SixHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شانزده.
        /// </summary>
        internal static string Number_Sixteen {
            get {
                return ResourceManager.GetString("Number_Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شصت.
        /// </summary>
        internal static string Number_Sixty {
            get {
                return ResourceManager.GetString("Number_Sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ده.
        /// </summary>
        internal static string Number_Ten {
            get {
                return ResourceManager.GetString("Number_Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیزده.
        /// </summary>
        internal static string Number_Thirteen {
            get {
                return ResourceManager.GetString("Number_Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سی.
        /// </summary>
        internal static string Number_Thirty {
            get {
                return ResourceManager.GetString("Number_Thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزار.
        /// </summary>
        internal static string Number_Thousand {
            get {
                return ResourceManager.GetString("Number_Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه.
        /// </summary>
        internal static string Number_Three {
            get {
                return ResourceManager.GetString("Number_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیصد.
        /// </summary>
        internal static string Number_ThreeHundred {
            get {
                return ResourceManager.GetString("Number_ThreeHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تریلیارد.
        /// </summary>
        internal static string Number_Trilliard {
            get {
                return ResourceManager.GetString("Number_Trilliard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تریلیون.
        /// </summary>
        internal static string Number_Trillion {
            get {
                return ResourceManager.GetString("Number_Trillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوازده.
        /// </summary>
        internal static string Number_Twelve {
            get {
                return ResourceManager.GetString("Number_Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست.
        /// </summary>
        internal static string Number_Twenty {
            get {
                return ResourceManager.GetString("Number_Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو.
        /// </summary>
        internal static string Number_Two {
            get {
                return ResourceManager.GetString("Number_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دویست.
        /// </summary>
        internal static string Number_TwoHundred {
            get {
                return ResourceManager.GetString("Number_TwoHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريال.
        /// </summary>
        internal static string Rial {
            get {
                return ResourceManager.GetString("Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        internal static string SaturdayPersian {
            get {
                return ResourceManager.GetString("SaturdayPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        internal static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ثانیه پیش.
        /// </summary>
        internal static string SecondsAgoPersian {
            get {
                return ResourceManager.GetString("SecondsAgoPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه.
        /// </summary>
        internal static string SundayPersian {
            get {
                return ResourceManager.GetString("SundayPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجشنبه.
        /// </summary>
        internal static string ThursdayPersian {
            get {
                return ResourceManager.GetString("ThursdayPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امروز.
        /// </summary>
        internal static string TodayPersian {
            get {
                return ResourceManager.GetString("TodayPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تومان.
        /// </summary>
        internal static string Toman {
            get {
                return ResourceManager.GetString("Toman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فردا.
        /// </summary>
        internal static string TomorrowPersian {
            get {
                return ResourceManager.GetString("TomorrowPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه شنبه.
        /// </summary>
        internal static string TuesdayPersian {
            get {
                return ResourceManager.GetString("TuesdayPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        internal static string WednesdayPersian {
            get {
                return ResourceManager.GetString("WednesdayPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks ago.
        /// </summary>
        internal static string WeekAgo {
            get {
                return ResourceManager.GetString("WeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} هفته پیش.
        /// </summary>
        internal static string WeekAgoPersian {
            get {
                return ResourceManager.GetString("WeekAgoPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Weeks Later.
        /// </summary>
        internal static string WeekLater {
            get {
                return ResourceManager.GetString("WeekLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} هفته بعد.
        /// </summary>
        internal static string WeekLaterPersian {
            get {
                return ResourceManager.GetString("WeekLaterPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیروز.
        /// </summary>
        internal static string YesterdayPersian {
            get {
                return ResourceManager.GetString("YesterdayPersian", resourceCulture);
            }
        }
    }
}
