//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuxiliaryLibraries.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuxiliaryLibraries.Resources.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه معتبر نمی باشد.
        /// </summary>
        public static string CellNumberIsNotValid {
            get {
                return ResourceManager.GetString("CellNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سیستم عامل.
        /// </summary>
        public static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل معتبر نمی باشد.
        /// </summary>
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} معتبر نمی باشد.
        /// </summary>
        public static string FieldIsNotValid {
            get {
                return ResourceManager.GetString("FieldIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} الزامی می باشد..
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما به این فایل غیر مجاز شناخته شده است..
        /// </summary>
        public static string FileAccessDenied {
            get {
                return ResourceManager.GetString("FileAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} معتبر نمی باشد، شما باید {0} را با پسوند {1} وارد نمائید..
        /// </summary>
        public static string FileIsNotValid {
            get {
                return ResourceManager.GetString("FileIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه فایل بزرگ است (حداکثر {0}). لطفا فایل کوچکتری انتخاب کنید..
        /// </summary>
        public static string FileIsTooBig {
            get {
                return ResourceManager.GetString("FileIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندازه فایل کوچک است (حداقل {0} ). لطفا فایل بزرگتری انتخاب کنید.
        /// </summary>
        public static string FileIsTooSmall {
            get {
                return ResourceManager.GetString("FileIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فایل وجود ندارد..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد تصویر مناسب نیست. حداکثر ابعاد تصویر باید {1}*{0} برحسب پیکسل باشد..
        /// </summary>
        public static string ImageMaxWithHeightIsInvalid {
            get {
                return ResourceManager.GetString("ImageMaxWithHeightIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد تصویر مناسب نیست. حداقل ابعاد تصویر باید {1}*{0} برحسب پیکسل باشد..
        /// </summary>
        public static string ImageMinWithHeightIsInvalid {
            get {
                return ResourceManager.GetString("ImageMinWithHeightIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبت طول به عرض (تقسیم عرض به طول) تصویر مناسب نیست. حداقل این نسبت باید {0} و حداکثر آن {1} باشد..
        /// </summary>
        public static string ImageRationIsInvalid {
            get {
                return ResourceManager.GetString("ImageRationIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل نامعتبر است.
        /// </summary>
        public static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات فایل هلپر معتبر نیست.
        /// </summary>
        public static string InvalidFileHelperSetting {
            get {
                return ResourceManager.GetString("InvalidFileHelperSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی تنظیمات فایل هلپر در اپلیکیشن ستینگ به درستی وارد نشده است.
        /// </summary>
        public static string InvalidFileHelperSettingException {
            get {
                return ResourceManager.GetString("InvalidFileHelperSettingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل نامعتبر است.
        /// </summary>
        public static string InvalidFileSize {
            get {
                return ResourceManager.GetString("InvalidFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هدر درخواست شما معتبر نمی باشد.
        /// </summary>
        public static string InvalidHeaders {
            get {
                return ResourceManager.GetString("InvalidHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی در هدر درخواستی که ارسال کرده اید مقادیری وجود دارد که معتبر نمی باشند.
        ///لطفا خط زیر را در Startup بعد از app.UseRouting(); کپی کنید:
        ///app.UseHttpContextMiddleware();.
        /// </summary>
        public static string InvalidHeadersInnerException {
            get {
                return ResourceManager.GetString("InvalidHeadersInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعداد ارسالی برای {0} می باید بین بازه {1} و {2} باشند.
        /// </summary>
        public static string NotInRange {
            get {
                return ResourceManager.GetString("NotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نمی تواند شامل کاراکترها و کلمات غیر مجاز باشد. همچنین طول {0} نمی تواند کمتر از {2} کاراکتر و بیشتر از {1} کاراکتر باشد.{3}.
        /// </summary>
        public static string StringLengthIsNotValid {
            get {
                return ResourceManager.GetString("StringLengthIsNotValid", resourceCulture);
            }
        }
    }
}
